apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: default
spec:
  selector:
    app: payment-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: webhook
      protocol: TCP
      port: 11000
      targetPort: 3000
  type: ClusterIP