name: payment project
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: build and tests
    runs-on: ubuntu-latest
    container: node:20

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U machafa"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      
      - uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: run build
        run: npm run build

      - name: run lint
        run: npm run lint

      - name: run tests
        run: npm test
      
      - name: run unit tests
        run: npm run test:unit
      
      - name: run integration tests
        run: npm run test:integration
      
      - name: build docker image
        run: docker build -t payment-api:latest .

    

      