name: CD - Production Deploy

on:
  workflow_run:
    workflows: ["CI - Quality Gates"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Build & Push to K8s
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/payment-api:latest
            ${{ secrets.DOCKER_USERNAME }}/payment-api:${{ github.sha }}

      - name: Setup kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          # Update the image in the deployment manifest
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/payment-api:${{ github.sha }}|g" k8s/deployment.yaml
          
          # Apply all manifests (Secrets, ConfigMaps, Deployment, Service)
          kubectl apply -f k8s/
          
          # Wait for rollout completion
          kubectl rollout status deployment/payment-api

          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          export MPESA_API_KEY=${{ secrets.MPESA_API_KEY }}

          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/payment-api:${{ github.sha }}|g" k8s/deployment.yaml
          
          # Aplicar manifestos
          kubectl apply -f k8s/
          
          # Monitorar o Rollout e fazer Rollback se falhar
          if ! kubectl rollout status deployment/payment-api --timeout=300s; then
            echo "Deploy failed! Rolling back..."
            kubectl rollout undo deployment/payment-api
            exit 1
          fi